# Site settings
title: "Jekyll Resume Template"
description: "A resume template for Jekyll and GitHub Pages sites."

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Onyebuchi John Nwokentah"
resume_title:                   "Data Scientist | Data Analyst"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "jnwokentah@gmail.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "(+44) 7407489624"
resume_contact_address:         "North East, UK"

resume_header_contact_info:     "742 Evergreen Terrace, Springfield • 555-7334 • jnwokentah@gmail.com"
display_header_contact_info:    "false"

resume_header_intro: |
  <br><br>
  I am a data analyst with strong expertise in transforming complex datasets into actionable insights and building data-driven solutions. I hold a Master’s degree in Data Science and have applied my skills to a variety of projects, including developing a fact-checking system using BERT transformers and FAISS vector databases with NLP frameworks like Hugging Face.<br><br>
  
  I am proficient in Python, R, SQL, and modern data analysis and visualization tools such as Tableau, Power BI, pandas, NumPy, Matplotlib, Seaborn, TensorFlow, PyTorch, spaCy, and NLTK.<br><br>

  I have delivered projects ranging from predicting customer behavior and analyzing public school performance to classifying tumors using machine learning and forecasting crime trends. These experiences have strengthened my ability to extract meaningful insights, build robust predictive models, and communicate complex findings effectively.<br><br>

  Beyond technical expertise, I bring project management experience and have led cross-functional initiatives, ensuring timely delivery and high-quality outcomes. I thrive in collaborative environments where analytical thinking, creativity, and attention to detail drive impactful solutions.<br><br>

  I remain committed to professional growth, continuously exploring emerging tools and techniques to enhance my data science expertise and deliver high-impact solutions.



# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "yes"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_skills:          true
resume_section_recognition:     true
resume_section_links:           true
resume_section_associations:    true
# resume_section_interests:       true

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  resume_github_url:            "https://github.com/BuchiJN"
  resume_linkedin_url:          "https://www.linkedin.com/in/onyebuchi-nwokentah"
resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
